#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace DriverSolutions.DAL	
{
	[Table("company_info")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class CompanyInfo : INotifyPropertyChanged
	{
		private uint _companyInfoID;
		[Column("CompanyInfoID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_companyInfoID")]
		public virtual uint CompanyInfoID
		{
			get
			{
				return this._companyInfoID;
			}
			set
			{
				if(this._companyInfoID != value)
				{
					this._companyInfoID = value;
					this.OnPropertyChanged("CompanyInfoID");
				}
			}
		}
		
		private string _companyName;
		[Column("CompanyName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyName")]
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				if(this._companyName != value)
				{
					this._companyName = value;
					this.OnPropertyChanged("CompanyName");
				}
			}
		}
		
		private string _companyCity;
		[Column("CompanyCity", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyCity")]
		public virtual string CompanyCity
		{
			get
			{
				return this._companyCity;
			}
			set
			{
				if(this._companyCity != value)
				{
					this._companyCity = value;
					this.OnPropertyChanged("CompanyCity");
				}
			}
		}
		
		private string _companyState;
		[Column("CompanyState", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyState")]
		public virtual string CompanyState
		{
			get
			{
				return this._companyState;
			}
			set
			{
				if(this._companyState != value)
				{
					this._companyState = value;
					this.OnPropertyChanged("CompanyState");
				}
			}
		}
		
		private string _companyPostCode;
		[Column("CompanyPostCode", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyPostCode")]
		public virtual string CompanyPostCode
		{
			get
			{
				return this._companyPostCode;
			}
			set
			{
				if(this._companyPostCode != value)
				{
					this._companyPostCode = value;
					this.OnPropertyChanged("CompanyPostCode");
				}
			}
		}
		
		private string _companyAddress;
		[Column("CompanyAddress", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyAddress")]
		public virtual string CompanyAddress
		{
			get
			{
				return this._companyAddress;
			}
			set
			{
				if(this._companyAddress != value)
				{
					this._companyAddress = value;
					this.OnPropertyChanged("CompanyAddress");
				}
			}
		}
		
		private string _companyManagerName;
		[Column("CompanyManagerName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyManagerName")]
		public virtual string CompanyManagerName
		{
			get
			{
				return this._companyManagerName;
			}
			set
			{
				if(this._companyManagerName != value)
				{
					this._companyManagerName = value;
					this.OnPropertyChanged("CompanyManagerName");
				}
			}
		}
		
		private string _companyInvoiceAddress;
		[Column("CompanyInvoiceAddress", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_companyInvoiceAddress")]
		public virtual string CompanyInvoiceAddress
		{
			get
			{
				return this._companyInvoiceAddress;
			}
			set
			{
				if(this._companyInvoiceAddress != value)
				{
					this._companyInvoiceAddress = value;
					this.OnPropertyChanged("CompanyInvoiceAddress");
				}
			}
		}
		
		private byte[] _companyLogo;
		[Column("CompanyLogo", OpenAccessType = OpenAccessType.LongVarBinary, IsNullable = true, Length = 0, Scale = 0, SqlType = "mediumblob")]
		[Storage("_companyLogo")]
		public virtual byte[] CompanyLogo
		{
			get
			{
				return this._companyLogo;
			}
			set
			{
				if(this._companyLogo != value)
				{
					this._companyLogo = value;
					this.OnPropertyChanged("CompanyLogo");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
