#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace DriverSolutions.DAL	
{
	[Table("const_contact_type")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class ConstContactType : INotifyPropertyChanged
	{
		private uint _conTypeID;
		[Column("ConTypeID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_conTypeID")]
		public virtual uint ConTypeID
		{
			get
			{
				return this._conTypeID;
			}
			set
			{
				if(this._conTypeID != value)
				{
					this._conTypeID = value;
					this.OnPropertyChanged("ConTypeID");
				}
			}
		}
		
		private string _conTypeName;
		[Column("ConTypeName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_conTypeName")]
		public virtual string ConTypeName
		{
			get
			{
				return this._conTypeName;
			}
			set
			{
				if(this._conTypeName != value)
				{
					this._conTypeName = value;
					this.OnPropertyChanged("ConTypeName");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
