#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("const_invoice_types")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class ConstInvoiceType : INotifyPropertyChanged
	{
		private uint _invoiceTypeID;
		[Column("InvoiceTypeID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_invoiceTypeID")]
		public virtual uint InvoiceTypeID
		{
			get
			{
				return this._invoiceTypeID;
			}
			set
			{
				if(this._invoiceTypeID != value)
				{
					this._invoiceTypeID = value;
					this.OnPropertyChanged("InvoiceTypeID");
				}
			}
		}
		
		private string _invoiceTypeName;
		[Column("InvoiceTypeName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_invoiceTypeName")]
		public virtual string InvoiceTypeName
		{
			get
			{
				return this._invoiceTypeName;
			}
			set
			{
				if(this._invoiceTypeName != value)
				{
					this._invoiceTypeName = value;
					this.OnPropertyChanged("InvoiceTypeName");
				}
			}
		}
		
		private IList<Invoice> _invoices = new List<Invoice>();
		[Collection(InverseProperty = "ConstInvoiceType")]
		[Storage("_invoices")]
		public virtual IList<Invoice> Invoices
		{
			get
			{
				return this._invoices;
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
