#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("const_permits")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class ConstPermit : INotifyPropertyChanged
	{
		private uint _permitID;
		[Column("PermitID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_permitID")]
		public virtual uint PermitID
		{
			get
			{
				return this._permitID;
			}
			set
			{
				if(this._permitID != value)
				{
					this._permitID = value;
					this.OnPropertyChanged("PermitID");
				}
			}
		}
		
		private string _permitName;
		[Column("PermitName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_permitName")]
		public virtual string PermitName
		{
			get
			{
				return this._permitName;
			}
			set
			{
				if(this._permitName != value)
				{
					this._permitName = value;
					this.OnPropertyChanged("PermitName");
				}
			}
		}
		
		private string _permitCode;
		[Column("PermitCode", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 20, Scale = 0, SqlType = "nvarchar")]
		[Storage("_permitCode")]
		public virtual string PermitCode
		{
			get
			{
				return this._permitCode;
			}
			set
			{
				if(this._permitCode != value)
				{
					this._permitCode = value;
					this.OnPropertyChanged("PermitCode");
				}
			}
		}
		
		private bool _isEnabled;
		[Column("IsEnabled", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isEnabled")]
		public virtual bool IsEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if(this._isEnabled != value)
				{
					this._isEnabled = value;
					this.OnPropertyChanged("IsEnabled");
				}
			}
		}
		
		private uint _permitPosition;
		[Column("PermitPosition", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_permitPosition")]
		public virtual uint PermitPosition
		{
			get
			{
				return this._permitPosition;
			}
			set
			{
				if(this._permitPosition != value)
				{
					this._permitPosition = value;
					this.OnPropertyChanged("PermitPosition");
				}
			}
		}
		
		private IList<DriversConstPermit> _driversConstPermits = new List<DriversConstPermit>();
		[Collection(InverseProperty = "ConstPermit")]
		[Storage("_driversConstPermits")]
		public virtual IList<DriversConstPermit> DriversConstPermits
		{
			get
			{
				return this._driversConstPermits;
			}
		}
		
		private IList<DriversLicensesPermit> _driversLicensesPermits = new List<DriversLicensesPermit>();
		[Collection(InverseProperty = "ConstPermit")]
		[Storage("_driversLicensesPermits")]
		public virtual IList<DriversLicensesPermit> DriversLicensesPermits
		{
			get
			{
				return this._driversLicensesPermits;
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
