#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace DriverSolutions.DAL	
{
	[Table("db_versions")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class DbVersion : INotifyPropertyChanged
	{
		private uint _versionID;
		[Column("VersionID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_versionID")]
		public virtual uint VersionID
		{
			get
			{
				return this._versionID;
			}
			set
			{
				if(this._versionID != value)
				{
					this._versionID = value;
					this.OnPropertyChanged("VersionID");
				}
			}
		}
		
		private string _versionNumber;
		[Column("VersionNumber", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_versionNumber")]
		public virtual string VersionNumber
		{
			get
			{
				return this._versionNumber;
			}
			set
			{
				if(this._versionNumber != value)
				{
					this._versionNumber = value;
					this.OnPropertyChanged("VersionNumber");
				}
			}
		}
		
		private bool _isReady;
		[Column("IsReady", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isReady")]
		public virtual bool IsReady
		{
			get
			{
				return this._isReady;
			}
			set
			{
				if(this._isReady != value)
				{
					this._isReady = value;
					this.OnPropertyChanged("IsReady");
				}
			}
		}
		
		private byte[] _versionPatcher;
		[Column("VersionPatcher", OpenAccessType = OpenAccessType.LongVarBinary, IsNullable = true, Length = 0, Scale = 0, SqlType = "mediumblob")]
		[Storage("_versionPatcher")]
		public virtual byte[] VersionPatcher
		{
			get
			{
				return this._versionPatcher;
			}
			set
			{
				if(this._versionPatcher != value)
				{
					this._versionPatcher = value;
					this.OnPropertyChanged("VersionPatcher");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
