#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("drivers_licenses_permits")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class DriversLicensesPermit : INotifyPropertyChanged
	{
		private uint _driverLicensePermitID;
		[Column("DriverLicensePermitID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_driverLicensePermitID")]
		public virtual uint DriverLicensePermitID
		{
			get
			{
				return this._driverLicensePermitID;
			}
			set
			{
				if(this._driverLicensePermitID != value)
				{
					this._driverLicensePermitID = value;
					this.OnPropertyChanged("DriverLicensePermitID");
				}
			}
		}
		
		private uint _driverLicenseID;
		[Column("DriverLicenseID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_driverLicenseID")]
		public virtual uint DriverLicenseID
		{
			get
			{
				return this._driverLicenseID;
			}
			set
			{
				if(this._driverLicenseID != value)
				{
					this._driverLicenseID = value;
					this.OnPropertyChanged("DriverLicenseID");
				}
			}
		}
		
		private uint _permitID;
		[Column("PermitID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_permitID")]
		public virtual uint PermitID
		{
			get
			{
				return this._permitID;
			}
			set
			{
				if(this._permitID != value)
				{
					this._permitID = value;
					this.OnPropertyChanged("PermitID");
				}
			}
		}
		
		private DriversLicense _driversLicense;
		[ForeignKeyAssociation(ConstraintName = "FK_drivers_licenses_permits_drivers_licenses_DriverLicenseID", SharedFields = "DriverLicenseID", TargetFields = "DriverLicenseID")]
		[Storage("_driversLicense")]
		public virtual DriversLicense DriversLicense
		{
			get
			{
				return this._driversLicense;
			}
			set
			{
				if(this._driversLicense != value)
				{
					this._driversLicense = value;
					this.OnPropertyChanged("DriversLicense");
				}
			}
		}
		
		private ConstPermit _constPermit;
		[ForeignKeyAssociation(ConstraintName = "FK_drivers_licenses_permits_const_permits_PermitID", SharedFields = "PermitID", TargetFields = "PermitID")]
		[Storage("_constPermit")]
		public virtual ConstPermit ConstPermit
		{
			get
			{
				return this._constPermit;
			}
			set
			{
				if(this._constPermit != value)
				{
					this._constPermit = value;
					this.OnPropertyChanged("ConstPermit");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
