#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("file_blobs")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class FileBlob : INotifyPropertyChanged
	{
		private uint _blobID;
		[Column("BlobID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_blobID")]
		public virtual uint BlobID
		{
			get
			{
				return this._blobID;
			}
			set
			{
				if(this._blobID != value)
				{
					this._blobID = value;
					this.OnPropertyChanged("BlobID");
				}
			}
		}
		
		private string _blobName;
		[Column("BlobName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_blobName")]
		public virtual string BlobName
		{
			get
			{
				return this._blobName;
			}
			set
			{
				if(this._blobName != value)
				{
					this._blobName = value;
					this.OnPropertyChanged("BlobName");
				}
			}
		}
		
		private string _blobDescription;
		[Column("BlobDescription", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_blobDescription")]
		public virtual string BlobDescription
		{
			get
			{
				return this._blobDescription;
			}
			set
			{
				if(this._blobDescription != value)
				{
					this._blobDescription = value;
					this.OnPropertyChanged("BlobDescription");
				}
			}
		}
		
		private byte[] _blobData;
		[Column("BlobData", OpenAccessType = OpenAccessType.LongVarBinary, Length = 0, Scale = 0, SqlType = "longblob")]
		[Storage("_blobData")]
		public virtual byte[] BlobData
		{
			get
			{
				return this._blobData;
			}
			set
			{
				if(this._blobData != value)
				{
					this._blobData = value;
					this.OnPropertyChanged("BlobData");
				}
			}
		}
		
		private uint? _driverID;
		[Column("DriverID", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_driverID")]
		public virtual uint? DriverID
		{
			get
			{
				return this._driverID;
			}
			set
			{
				if(this._driverID != value)
				{
					this._driverID = value;
					this.OnPropertyChanged("DriverID");
				}
			}
		}
		
		private uint _userID;
		[Column("UserID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_userID")]
		public virtual uint UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if(this._userID != value)
				{
					this._userID = value;
					this.OnPropertyChanged("UserID");
				}
			}
		}
		
		private DateTime _lastUpdateTime;
		[Column("LastUpdateTime", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "timestamp")]
		[Storage("_lastUpdateTime")]
		public virtual DateTime LastUpdateTime
		{
			get
			{
				return this._lastUpdateTime;
			}
			set
			{
				if(this._lastUpdateTime != value)
				{
					this._lastUpdateTime = value;
					this.OnPropertyChanged("LastUpdateTime");
				}
			}
		}
		
		private string _blobExtension;
		[Column("BlobExtension", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 10, Scale = 0, SqlType = "nvarchar")]
		[Storage("_blobExtension")]
		public virtual string BlobExtension
		{
			get
			{
				return this._blobExtension;
			}
			set
			{
				if(this._blobExtension != value)
				{
					this._blobExtension = value;
					this.OnPropertyChanged("BlobExtension");
				}
			}
		}
		
		private User _user;
		[ForeignKeyAssociation(ConstraintName = "FK_file_blobs_users_UserID", SharedFields = "UserID", TargetFields = "UserID")]
		[Storage("_user")]
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				if(this._user != value)
				{
					this._user = value;
					this.OnPropertyChanged("User");
				}
			}
		}
		
		private Driver _driver;
		[ForeignKeyAssociation(ConstraintName = "FK_file_blobs_drivers_DriverID", SharedFields = "DriverID", TargetFields = "DriverID")]
		[Storage("_driver")]
		public virtual Driver Driver
		{
			get
			{
				return this._driver;
			}
			set
			{
				if(this._driver != value)
				{
					this._driver = value;
					this.OnPropertyChanged("Driver");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
