#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("file_objects")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class FileObject : INotifyPropertyChanged
	{
		private uint _fileID;
		[Column("FileID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_fileID")]
		public virtual uint FileID
		{
			get
			{
				return this._fileID;
			}
			set
			{
				if(this._fileID != value)
				{
					this._fileID = value;
					this.OnPropertyChanged("FileID");
				}
			}
		}
		
		private string _fileName;
		[Column("FileName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fileName")]
		public virtual string FileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				if(this._fileName != value)
				{
					this._fileName = value;
					this.OnPropertyChanged("FileName");
				}
			}
		}
		
		private byte[] _fileBlob;
		[Column("FileBlob", OpenAccessType = OpenAccessType.LongVarBinary, Length = 0, Scale = 0, SqlType = "mediumblob")]
		[Storage("_fileBlob")]
		public virtual byte[] FileBlob
		{
			get
			{
				return this._fileBlob;
			}
			set
			{
				if(this._fileBlob != value)
				{
					this._fileBlob = value;
					this.OnPropertyChanged("FileBlob");
				}
			}
		}
		
		private string _fileExtension;
		[Column("FileExtension", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fileExtension")]
		public virtual string FileExtension
		{
			get
			{
				return this._fileExtension;
			}
			set
			{
				if(this._fileExtension != value)
				{
					this._fileExtension = value;
					this.OnPropertyChanged("FileExtension");
				}
			}
		}
		
		private string _fileDescription;
		[Column("FileDescription", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fileDescription")]
		public virtual string FileDescription
		{
			get
			{
				return this._fileDescription;
			}
			set
			{
				if(this._fileDescription != value)
				{
					this._fileDescription = value;
					this.OnPropertyChanged("FileDescription");
				}
			}
		}
		
		private IList<Report> _reports = new List<Report>();
		[Collection(InverseProperty = "FileObject")]
		[Storage("_reports")]
		public virtual IList<Report> Reports
		{
			get
			{
				return this._reports;
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
