#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("invoices_details")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class InvoicesDetail : INotifyPropertyChanged
	{
		private uint _invoiceDetailID;
		[Column("InvoiceDetailID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_invoiceDetailID")]
		public virtual uint InvoiceDetailID
		{
			get
			{
				return this._invoiceDetailID;
			}
			set
			{
				if(this._invoiceDetailID != value)
				{
					this._invoiceDetailID = value;
					this.OnPropertyChanged("InvoiceDetailID");
				}
			}
		}
		
		private uint _invoiceID;
		[Column("InvoiceID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_invoiceID")]
		public virtual uint InvoiceID
		{
			get
			{
				return this._invoiceID;
			}
			set
			{
				if(this._invoiceID != value)
				{
					this._invoiceID = value;
					this.OnPropertyChanged("InvoiceID");
				}
			}
		}
		
		private DateTime? _invoiceDetailDate;
		[Column("InvoiceDetailDate", OpenAccessType = OpenAccessType.Date, IsNullable = true, Length = 0, Scale = 0, SqlType = "date")]
		[Storage("_invoiceDetailDate")]
		public virtual DateTime? InvoiceDetailDate
		{
			get
			{
				return this._invoiceDetailDate;
			}
			set
			{
				if(this._invoiceDetailDate != value)
				{
					this._invoiceDetailDate = value;
					this.OnPropertyChanged("InvoiceDetailDate");
				}
			}
		}
		
		private string _invoiceDetailName;
		[Column("InvoiceDetailName", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_invoiceDetailName")]
		public virtual string InvoiceDetailName
		{
			get
			{
				return this._invoiceDetailName;
			}
			set
			{
				if(this._invoiceDetailName != value)
				{
					this._invoiceDetailName = value;
					this.OnPropertyChanged("InvoiceDetailName");
				}
			}
		}
		
		private decimal _invoiceDetailOverTime;
		[Column("InvoiceDetailOverTime", OpenAccessType = OpenAccessType.Decimal, Length = 10, Scale = 2, SqlType = "decimal unsigned")]
		[Storage("_invoiceDetailOverTime")]
		public virtual decimal InvoiceDetailOverTime
		{
			get
			{
				return this._invoiceDetailOverTime;
			}
			set
			{
				if(this._invoiceDetailOverTime != value)
				{
					this._invoiceDetailOverTime = value;
					this.OnPropertyChanged("InvoiceDetailOverTime");
				}
			}
		}
		
		private decimal _invoiceDetailRegularRate;
		[Column("InvoiceDetailRegularRate", OpenAccessType = OpenAccessType.Decimal, Length = 10, Scale = 2, SqlType = "decimal unsigned")]
		[Storage("_invoiceDetailRegularRate")]
		public virtual decimal InvoiceDetailRegularRate
		{
			get
			{
				return this._invoiceDetailRegularRate;
			}
			set
			{
				if(this._invoiceDetailRegularRate != value)
				{
					this._invoiceDetailRegularRate = value;
					this.OnPropertyChanged("InvoiceDetailRegularRate");
				}
			}
		}
		
		private decimal _invoiceDetailOverRate;
		[Column("InvoiceDetailOverRate", OpenAccessType = OpenAccessType.Decimal, Length = 10, Scale = 2, SqlType = "decimal unsigned")]
		[Storage("_invoiceDetailOverRate")]
		public virtual decimal InvoiceDetailOverRate
		{
			get
			{
				return this._invoiceDetailOverRate;
			}
			set
			{
				if(this._invoiceDetailOverRate != value)
				{
					this._invoiceDetailOverRate = value;
					this.OnPropertyChanged("InvoiceDetailOverRate");
				}
			}
		}
		
		private decimal _invoiceDetailRegularPay;
		[Column("InvoiceDetailRegularPay", OpenAccessType = OpenAccessType.Decimal, Length = 10, Scale = 2, SqlType = "decimal unsigned")]
		[Storage("_invoiceDetailRegularPay")]
		public virtual decimal InvoiceDetailRegularPay
		{
			get
			{
				return this._invoiceDetailRegularPay;
			}
			set
			{
				if(this._invoiceDetailRegularPay != value)
				{
					this._invoiceDetailRegularPay = value;
					this.OnPropertyChanged("InvoiceDetailRegularPay");
				}
			}
		}
		
		private decimal _invoiceDetailOvertimePay;
		[Column("InvoiceDetailOvertimePay", OpenAccessType = OpenAccessType.Decimal, Length = 10, Scale = 2, SqlType = "decimal unsigned")]
		[Storage("_invoiceDetailOvertimePay")]
		public virtual decimal InvoiceDetailOvertimePay
		{
			get
			{
				return this._invoiceDetailOvertimePay;
			}
			set
			{
				if(this._invoiceDetailOvertimePay != value)
				{
					this._invoiceDetailOvertimePay = value;
					this.OnPropertyChanged("InvoiceDetailOvertimePay");
				}
			}
		}
		
		private decimal _invoiceDetailTotalTime;
		[Column("InvoiceDetailTotalTime", OpenAccessType = OpenAccessType.Decimal, Length = 10, Scale = 2, SqlType = "decimal unsigned")]
		[Storage("_invoiceDetailTotalTime")]
		public virtual decimal InvoiceDetailTotalTime
		{
			get
			{
				return this._invoiceDetailTotalTime;
			}
			set
			{
				if(this._invoiceDetailTotalTime != value)
				{
					this._invoiceDetailTotalTime = value;
					this.OnPropertyChanged("InvoiceDetailTotalTime");
				}
			}
		}
		
		private uint _invoiceDetailGroupPosition;
		[Column("InvoiceDetailGroupPosition", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_invoiceDetailGroupPosition")]
		public virtual uint InvoiceDetailGroupPosition
		{
			get
			{
				return this._invoiceDetailGroupPosition;
			}
			set
			{
				if(this._invoiceDetailGroupPosition != value)
				{
					this._invoiceDetailGroupPosition = value;
					this.OnPropertyChanged("InvoiceDetailGroupPosition");
				}
			}
		}
		
		private string _invoiceDetailGroupName;
		[Column("InvoiceDetailGroupName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_invoiceDetailGroupName")]
		public virtual string InvoiceDetailGroupName
		{
			get
			{
				return this._invoiceDetailGroupName;
			}
			set
			{
				if(this._invoiceDetailGroupName != value)
				{
					this._invoiceDetailGroupName = value;
					this.OnPropertyChanged("InvoiceDetailGroupName");
				}
			}
		}
		
		private Invoice _invoice;
		[ForeignKeyAssociation(ConstraintName = "FK_invoices_details_invoices_InvoiceID", SharedFields = "InvoiceID", TargetFields = "InvoiceID")]
		[Storage("_invoice")]
		public virtual Invoice Invoice
		{
			get
			{
				return this._invoice;
			}
			set
			{
				if(this._invoice != value)
				{
					this._invoice = value;
					this.OnPropertyChanged("Invoice");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
