#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace DriverSolutions.DAL	
{
	[Table("logs")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Log : INotifyPropertyChanged
	{
		private uint _logID;
		[Column("LogID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_logID")]
		public virtual uint LogID
		{
			get
			{
				return this._logID;
			}
			set
			{
				if(this._logID != value)
				{
					this._logID = value;
					this.OnPropertyChanged("LogID");
				}
			}
		}
		
		private byte _logType;
		[Column("LogType", OpenAccessType = OpenAccessType.Byte, Length = 0, Scale = 0, SqlType = "tinyint unsigned")]
		[Storage("_logType")]
		public virtual byte LogType
		{
			get
			{
				return this._logType;
			}
			set
			{
				if(this._logType != value)
				{
					this._logType = value;
					this.OnPropertyChanged("LogType");
				}
			}
		}
		
		private string _logLocation;
		[Column("LogLocation", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_logLocation")]
		public virtual string LogLocation
		{
			get
			{
				return this._logLocation;
			}
			set
			{
				if(this._logLocation != value)
				{
					this._logLocation = value;
					this.OnPropertyChanged("LogLocation");
				}
			}
		}
		
		private string _logMessage;
		[Column("LogMessage", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "text")]
		[Storage("_logMessage")]
		public virtual string LogMessage
		{
			get
			{
				return this._logMessage;
			}
			set
			{
				if(this._logMessage != value)
				{
					this._logMessage = value;
					this.OnPropertyChanged("LogMessage");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
