#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("reports")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Report : INotifyPropertyChanged
	{
		private uint _reportID;
		[Column("ReportID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_reportID")]
		public virtual uint ReportID
		{
			get
			{
				return this._reportID;
			}
			set
			{
				if(this._reportID != value)
				{
					this._reportID = value;
					this.OnPropertyChanged("ReportID");
				}
			}
		}
		
		private string _reportName;
		[Column("ReportName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_reportName")]
		public virtual string ReportName
		{
			get
			{
				return this._reportName;
			}
			set
			{
				if(this._reportName != value)
				{
					this._reportName = value;
					this.OnPropertyChanged("ReportName");
				}
			}
		}
		
		private uint _queryID;
		[Column("QueryID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_queryID")]
		public virtual uint QueryID
		{
			get
			{
				return this._queryID;
			}
			set
			{
				if(this._queryID != value)
				{
					this._queryID = value;
					this.OnPropertyChanged("QueryID");
				}
			}
		}
		
		private uint _fileID;
		[Column("FileID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_fileID")]
		public virtual uint FileID
		{
			get
			{
				return this._fileID;
			}
			set
			{
				if(this._fileID != value)
				{
					this._fileID = value;
					this.OnPropertyChanged("FileID");
				}
			}
		}
		
		private SqlQuery _sqlQuery;
		[ForeignKeyAssociation(ConstraintName = "FK_reports_sql_queries_QueryID", SharedFields = "QueryID", TargetFields = "QueryID")]
		[Storage("_sqlQuery")]
		public virtual SqlQuery SqlQuery
		{
			get
			{
				return this._sqlQuery;
			}
			set
			{
				if(this._sqlQuery != value)
				{
					this._sqlQuery = value;
					this.OnPropertyChanged("SqlQuery");
				}
			}
		}
		
		private FileObject _fileObject;
		[ForeignKeyAssociation(ConstraintName = "FK_reports_file_objects_FileID", SharedFields = "FileID", TargetFields = "FileID")]
		[Storage("_fileObject")]
		public virtual FileObject FileObject
		{
			get
			{
				return this._fileObject;
			}
			set
			{
				if(this._fileObject != value)
				{
					this._fileObject = value;
					this.OnPropertyChanged("FileObject");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
