#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace DriverSolutions.DAL	
{
	[Table("settings")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Setting : INotifyPropertyChanged
	{
		private uint _settingID;
		[Column("SettingID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_settingID")]
		public virtual uint SettingID
		{
			get
			{
				return this._settingID;
			}
			set
			{
				if(this._settingID != value)
				{
					this._settingID = value;
					this.OnPropertyChanged("SettingID");
				}
			}
		}
		
		private string _settingValue;
		[Column("SettingValue", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_settingValue")]
		public virtual string SettingValue
		{
			get
			{
				return this._settingValue;
			}
			set
			{
				if(this._settingValue != value)
				{
					this._settingValue = value;
					this.OnPropertyChanged("SettingValue");
				}
			}
		}
		
		private string _settingDescription;
		[Column("SettingDescription", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_settingDescription")]
		public virtual string SettingDescription
		{
			get
			{
				return this._settingDescription;
			}
			set
			{
				if(this._settingDescription != value)
				{
					this._settingDescription = value;
					this.OnPropertyChanged("SettingDescription");
				}
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
