#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using DriverSolutions.DAL;

namespace DriverSolutions.DAL	
{
	[Table("users")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class User : INotifyPropertyChanged
	{
		private uint _userID;
		[Column("UserID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "integer unsigned")]
		[Storage("_userID")]
		public virtual uint UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if(this._userID != value)
				{
					this._userID = value;
					this.OnPropertyChanged("UserID");
				}
			}
		}
		
		private string _username;
		[Column("Username", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 255, Scale = 0, SqlType = "nvarchar")]
		[Storage("_username")]
		public virtual string Username
		{
			get
			{
				return this._username;
			}
			set
			{
				if(this._username != value)
				{
					this._username = value;
					this.OnPropertyChanged("Username");
				}
			}
		}
		
		private string _password;
		[Column("Password", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 128, Scale = 0, SqlType = "nvarchar")]
		[Storage("_password")]
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				if(this._password != value)
				{
					this._password = value;
					this.OnPropertyChanged("Password");
				}
			}
		}
		
		private string _firstName;
		[Column("FirstName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_firstName")]
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if(this._firstName != value)
				{
					this._firstName = value;
					this.OnPropertyChanged("FirstName");
				}
			}
		}
		
		private string _secondName;
		[Column("SecondName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_secondName")]
		public virtual string SecondName
		{
			get
			{
				return this._secondName;
			}
			set
			{
				if(this._secondName != value)
				{
					this._secondName = value;
					this.OnPropertyChanged("SecondName");
				}
			}
		}
		
		private string _lastName;
		[Column("LastName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_lastName")]
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if(this._lastName != value)
				{
					this._lastName = value;
					this.OnPropertyChanged("LastName");
				}
			}
		}
		
		private bool _isEnabled;
		[Column("IsEnabled", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isEnabled")]
		public virtual bool IsEnabled
		{
			get
			{
				return this._isEnabled;
			}
			set
			{
				if(this._isEnabled != value)
				{
					this._isEnabled = value;
					this.OnPropertyChanged("IsEnabled");
				}
			}
		}
		
		private bool _isAdmin;
		[Column("IsAdmin", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isAdmin")]
		public virtual bool IsAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if(this._isAdmin != value)
				{
					this._isAdmin = value;
					this.OnPropertyChanged("IsAdmin");
				}
			}
		}
		
		private IList<Invoice> _invoices = new List<Invoice>();
		[Collection(InverseProperty = "User")]
		[Storage("_invoices")]
		public virtual IList<Invoice> Invoices
		{
			get
			{
				return this._invoices;
			}
		}
		
		private IList<Dispatch> _dispatches = new List<Dispatch>();
		[Collection(InverseProperty = "User")]
		[Storage("_dispatches")]
		public virtual IList<Dispatch> Dispatches
		{
			get
			{
				return this._dispatches;
			}
		}
		
		private IList<FileBlob> _fileBlobs = new List<FileBlob>();
		[Collection(InverseProperty = "User")]
		[Storage("_fileBlobs")]
		public virtual IList<FileBlob> FileBlobs
		{
			get
			{
				return this._fileBlobs;
			}
		}
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
